server:
  port: 8080
spring:
  application:
    name: conductor-boot-wrapper-oauth2-embedded-mariadb4j
  datasource:
    name: conductor
#    url: jdbc:mysql://localhost:3306/oauth?createDatabaseIfNotExist=true&autoReconnect=true&verifyServerCertificate=false&useSSL=false
    username: AnsiCon
    password: AnsiCon!23$
#    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    initialization-mode: never
    platform: mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true

check-user-scopes: true
awaitTermination: 300

#wrapper_db: mysql
wrapper_db: mariadb4j

mariadb4j:
  database:
    name: ${spring.datasource.name}
  dataDir: ./${spring.application.name}-data
  libDir: ./${spring.application.name}-lib
  baseDir: ./${spring.application.name}-base
#  dataDir: /appln/db/${spring.application.name}-data
#  libDir: /appln/db/${spring.application.name}-lib
#  baseDir: /appln/db/${spring.application.name}-base
  maxConnections: 100000
  wait: 
    timeout: 18000000
  connect:
    timeout: 31536000
  deleteBaseAndDataDirOnShutdown: false
  security:
    disabled: true

logbook:
  filter:
    enabled: true
  write:
    level: info
    chunk-size: 10000
  format:
    style: splunk
  exclude: [/conductor/api/swagger-ui**,/v3/api-docs/**,/actuator/**]
  strategy: body-only-if-status-at-least
  minimum-status: 400

## Conductor MYSQL Configuration for Hikari DataSource
db: mysql
jdbc:
#  url: ## Leave it commented for mariadb4j
  username: ${spring.datasource.username}
  password: ${spring.datasource.password}  
conductor:
  jetty:
    server:
      port: 8081
  mysql:
    connection:
      timeout: 18000000
      idle:
        timeout: 31536000 
      pool:
        idle:
          min: 2
        size:
          max: 10000

zuul:
  sensitive-headers:
  - Authorization
  routes:
    conductor:
      path: /conductor/**
      url: http://localhost:${conductor.jetty.server.port}
      retryable: true

security:
  oauth2:
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgnEzp25qlRJqe/IWf88o
          lfkOl9a7tX4wgDrLLzguzMIAHdLv2do1qb48nPJPJYElD6wVTguokOTOND+4oFzJ
          Oob/t/6cQ65gPCXVo8OfN1jrternBEIu9t2FuSmn/Ica+JvIZ4NJFz1UnxY1fYGv
          WMjsMwpOZk8uU39Pu8ywyyaRPXYi0Sbk8vj35GjdwkhshBOUaE45JlZpBms6HerY
          45TBbHTiC9hFQ8slwEd8DIsLYhSlogmCC7hciOVlNEJxUoumq1M20wlizkWhxCyM
          Q/5OZMLDBzhK7+lgp9M3ZUdJFOgNKbkR/gdktWC4RZxp90t+Ztct6pHoNz5K/0ji
          ZwIDAQAB
          -----END PUBLIC KEY-----